name: Juv-Workspace CI

on:
  push:
    branches:
      - main # Or your main branch
  pull_request:
    branches:
      - main # Or your main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Angular 17+ requires Node 18 or higher, 20 is a good choice

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build (Check for errors)
        run: npm run build -- --configuration=production --output-hashing=none # or ng build --configuration=production --output-hashing=none.

      - name: Test (Headless Chrome)
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Storybook (if applicable)
        run: npm run build-storybook || true # if storybook does not exist, do not fail.

      - name: Check for vulnerabilities
        run: npm audit --audit-level=high || true # if high vulnerabilities are found, do not fail.